{{- if .Values.ingress.backendHTTPS -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "goldfish.fullname" . }}-tls"
  labels:
    app: "{{ template "goldfish.name" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  {{- $files := .Files }}
  {{- range tuple "goldfish-certificate.cert" "goldfish-key.pem" }}
  {{ . }}: |-
    {{ $files.Get . | b64enc }}
  {{- end }}
{{- end }}
